FROM ubuntu:18.04
ENV LANG C.UTF-8
RUN apt-get update \
  && apt-get install -y apt-utils python3 python3-distutils python3-dev python3-venv git \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/testrunner
RUN /opt/testrunner/bin/pip install -U pip wheel setuptools pytest
RUN mkdir /work/
WORKDIR /work
